name: taskmate
description: A simple but powerful task management app. You can manage your task very efficiently using this app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  hexcolor: ^3.0.1
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
